title: "hw4"
output: html_document
author: Nan Chen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# access the Yarn cluster
options(scipen=200)
if (!require("pacman"))  
  install.packages("pacman", repos = "http://cran.us.r-project.org/")
library(pacman)
p_load("sparklyr", "dplyr", "ggplot2", "ggmap", "maps", "mapdata", 
           "devtools", "ggrepel", "lubridate", "RColorBrewer")
Sys.setenv(SPARK_HOME="/usr/lib/spark")
config <- spark_config()
sc <- spark_connect(master = "yarn-client", config = config)
```

```{r}
# connect the Hive tables
flights_tbl <- tbl(sc, 'flights')
flights_tbl %>% print(width = Inf)
airlines_tbl <- tbl(sc, 'airlines')
airlines_tbl %>% print(width = Inf)
airports_tbl <- tbl(sc, 'airports')
airports_tbl %>% print(width = Inf)
```

```{r}
# extract data in 2008
flights2008 <- flights_tbl %>% filter(origin != "Origin") %>%
  select(year, origin, dest) %>% filter(year == 2008)

airports <- airports_tbl %>% select(name, faa, lat, lon)

# destination with # of flights
dest <- dplyr::left_join(flights2008, airports, by = c("dest" = "faa")) %>%
  group_by(dest) %>% summarise(n = n()) %>% collect() %>% arrange(desc(n)) %>%
  select("airport" = dest, n)

# origin with # of flights
origin <- dplyr::left_join(flights2008, airports, by = c("origin" = "faa")) %>%
  group_by(origin) %>% summarise(n = n()) %>% collect() %>% arrange(desc(n)) %>%
  select("airport" = origin, n)
```


1. Map the top 10 busiest airports. Size of dots should reflect the number of flights through that destination.  
```{r}
# add dest and origin together and print out top 10
combine <- bind_rows(dest, origin) %>%
  group_by(airport) %>% summarise(sum = sum(n)) %>% arrange(desc(sum)) %>%
  head(10)

# pick out airports info for top 10
infotop10 <- airports %>% filter(faa %in% combine$airport) %>% collect()
    
top10 <- left_join(combine, infotop10, by = c("airport" = "faa")) %>%
      transmute(airport = airport, totflights = sum, lat = as.numeric(lat), 
                lon = as.numeric(lon), name = name)

usa <- map_data("usa")
states <- map_data("state")
ggplot() +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_polygon(data = states, aes(x = states$lon, y = states$lat, fill = region, 
                                  group = group), color = "white") +
  geom_point(data = top10, aes(x = lon, y = lat, size = totflights)) +
  labs(x = "Longitude", y = "Latitude", 
        title = "Top 10 Busiest Airports in 2008", size = "Total Flights") +
  geom_label_repel(data = top10, aes(x = lon, y = lat, label = airport)) +
  coord_fixed(1.3) + guides(fill = FALSE)
```