---
title: "hw3"
author: "Nan Chen"
date: "2/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
    if (!"DBI" %in% rownames(installed.packages()))  
      install.packages("DBI", repos = "http://cran.rstudio.com/")
    if (!"RSQLite" %in% rownames(installed.packages()))  
      install.packages("RSQLite", repos = "http://cran.rstudio.com/") 
    if (!"tidyverse" %in% rownames(installed.packages()))  
      install.packages("tidyverse", repos = "http://cran.rstudio.com/")
    if (!"dplyr" %in% rownames(installed.packages()))  
      install.packages("dplyr", repos = "http://cran.rstudio.com/")
suppressMessages(library("DBI"))
suppressMessages(library("RSQLite"))
suppressMessages(library("tidyverse"))
suppressMessages(library("dplyr"))
con <- dbConnect(RSQLite::SQLite(), 
                "/home/m280-data/la_parking/LA_Parking_Citations_Extra.sqlite")
```

```{r}
dbListTables(con)
res <- dbSendQuery(con, "SELECT count(Ticket_number) FROM latix")
```

